### ISSUE TITLE
当前仓库的数据文件和https://docschina.org页面上的数据为什么不一致

### ISSUE THREAD

**Issue by MwumLi** [docschina/docschina#1]
我从 web 页面来到这里, 以为当前仓库就是 docschina.org 的仓库, 结果发现里面的数据和web就不一样，并且样式也不一致, 这是为什么？

**Comment by dear-lizhihua** [comment]
现在是私有仓库，这个公共仓库应该清理下。
我们把数据放到这个仓库，然后私有仓库那边，同步拉取这边的文件？ @lcxfs1991 @QC-L

**Comment by lcxfs1991** [comment]
@MwumLi 这个repo已经outdated了。
@dear-lizhihua 可以放份数据在这里，然后同步。

**Comment by dear-lizhihua** [comment]
OK，那我直接 git push -f  强制推送了

**Comment by MwumLi** [comment]
@lcxfs1991 @dear-lizhihua  你们是希望开源社区来贡献数据来完善这个数据文件吗?

**Comment by dear-lizhihua** [comment]
我指的不是指导航列表的数据，这个列表我来维护，我指的是以后可能会有 markdown 或其他需要用户帮助我们改进的功能
