### ISSUE TITLE
web 页面pc端侧边栏超出

### ISSUE THREAD

**Issue by MwumLi** [docschina/docschina#2]
web 页面的 pc 端的样式出现问题, 如下图
<img width="442" alt="ybjivswf" src="https://user-images.githubusercontent.com/6889433/36651227-b7d67010-1ae2-11e8-9f4b-880f382c7a13.png">

**Comment by dear-lizhihua** [comment]
这不是 bug，是 feature……

**Comment by MwumLi** [comment]
@dear-lizhihua 你说的 feature 是什么意思? 是指的是水平居中吗? 如果是这个的话, 那么这个增强比较突兀, 看起来给人的感觉就像是左边侧边栏超出?

**Comment by dear-lizhihua** [comment]
是的，可能是你的屏幕宽度分辨率小，我在mac 1440px 确实有你说的那种情况，不过现在1080p比较普及了，主要还是针对 1920px 的用户

**Comment by dear-lizhihua** [comment]
我们的新页面，会逐渐向奇舞周刊、taobaofed.org 这些网站风格靠拢

**Comment by MwumLi** [comment]
我的就是 mac, 分辨率是 1920px, 我知道奇舞周刊这些站点的风格, 但是你们这个现在这个展现确实有点突兀,  只是提个建议, 你们自己看吧😂

**Comment by dear-lizhihua** [comment]
非常感谢建议，其实我想说的靠拢完左边的菜单可能就不存在了，我准备把他放内容区的上面，滑稽……

**Comment by MwumLi** [comment]
👍
